# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - spot_arm_controller
    - grip_controller

  spot_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - arm_sh0
      - arm_sh1
      - arm_el0
      - arm_el1
      - arm_wr0
      - arm_wr1
    action_ns: follow_joint_trajectory
    default: true
  grip_controller:
    type: GripperCommand
    joints:
      - arm_f1x
      - left_finger_joint
      - right_finger_joint
    action_ns: gripper_cmd
    default: true