controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    spot_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    grip_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

spot_arm_controller:
  ros__parameters:
    joints:
      - arm_sh0
      - arm_sh1
      - arm_el0
      - arm_el1
      - arm_wr0
      - arm_wr1
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
grip_controller:
  ros__parameters:
    joint: arm_f1x