controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    hand_controller:
      type: position_controllers/GripperActionController

hand_controller:
  ros__parameters:
    joint: arm_f1x